/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as Vue from "vue"

export const Index: Record<string, any> = {
  "button": {
    name: "button",
    description: "A flexible button component with multiple variants and sizes",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/default/ui/button.vue",
      type: "file",
      target: "components/ui/button.vue"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@/registry/default/ui/button.vue")
      return mod.default || mod
    }),
    categories: undefined,
    meta: undefined,
  },
  "utils": {
    name: "utils",
    description: "BEM className utility for Vue components",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/default//lib/utils.ts",
      type: "file",
      target: "lib/utils.ts"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@/registry/default//lib/utils.ts")
      return mod.default || mod
    }),
    categories: undefined,
    meta: undefined,
  },
  "index": {
    name: "index",
    description: "Base style system with SCSS variables and mixins",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [{
      path: "registry/default/assets/styles/_variables.scss",
      type: "file",
      target: "assets/styles/_variables.scss"
    },{
      path: "registry/default/assets/styles/_mixins.scss",
      type: "file",
      target: "assets/styles/_mixins.scss"
    },{
      path: "registry/default/assets/styles/_main.scss",
      type: "file",
      target: "assets/styles/_main.scss"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@/registry/default/assets/styles/_variables.scss")
      return mod.default || mod
    }),
    categories: undefined,
    meta: undefined,
  },
  }