/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as Vue from "vue"

export const Index: Record<string, any> = {
  "button": {
    name: "button",
    description: "A flexible button component with multiple variants and sizes",
    type: "registry:ui",
    registryDependencies: ["utils"],
    files: [{
      path: "@@/registry/default/ui/button.vue",
      type: "registry:ui",
      target: "button.vue"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@@/registry/default/ui/button.vue")
      return mod.default || mod
    }),
    category: "",
  },
  "utils": {
    name: "utils",
    description: "BEM className utility for Vue components",
    type: "registry:lib",
    registryDependencies: [],
    files: [{
      path: "@@/registry/default//lib/utils.ts",
      type: "registry:lib",
      target: "utils.ts"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@@/registry/default//lib/utils.ts")
      return mod.default || mod
    }),
    category: "",
  },
  "index": {
    name: "index",
    description: "Base style system with SCSS variables and mixins",
    type: "registry:style",
    registryDependencies: ["utils","useTheme"],
    files: [{
      path: "@@/registry/default/styles/_variables.scss",
      type: "registry:style",
      target: "_variables.scss"
    },{
      path: "@@/registry/default/styles/_mixins.scss",
      type: "registry:style",
      target: "_mixins.scss"
    },{
      path: "@@/registry/default/styles/_main.scss",
      type: "registry:style",
      target: "main.scss"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@@/registry/default/styles/_variables.scss")
      return mod.default || mod
    }),
    category: "",
  },
  "useTheme": {
    name: "useTheme",
    description: "Enhanced theme management composable with support for both light/dark modes and custom themes",
    type: "registry:composable",
    registryDependencies: [],
    files: [{
      path: "@@/registry/default/composables/useTheme.ts",
      type: "registry:composable",
      target: "useTheme.ts"
    }],
    component: Vue.defineAsyncComponent(async () => {
      const mod = await import("@@/registry/default/composables/useTheme.ts")
      return mod.default || mod
    }),
    category: "",
  },
}